upstream cluster {
    server gweb1:8080;
    server gweb2:8080;
    server gweb3:8080;
    server gweb4:8080;
    server gweb5:8080;
    server gweb6:8080;
    server gweb7:8080;
    server gweb8:8080;
    server gweb9:8080;
}

server {
    listen 80;
    location / {
        proxy_pass http://cluster;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
