upstream cluster {
    server raft1:8080;
    server raft2:8080;
    server raft3:8080;
    server raft4:8080;
    server raft5:8080;
    server raft6:8080;
    server raft7:8080;
    server raft8:8080;
    server raft9:8080;
}

server {
    listen 80;
    location / {
        proxy_pass http://cluster;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
